#!/bin/bash

function current() {
	readlink -f /etc/localtime | sed 's;/usr/share/zoneinfo/;;'
}

function available() {
	cat /usr/share/zoneinfo/zone1970.tab | grep -v "^#" | awk '{ print $3 }' | sort -u | tr '\n' ','
}

cmd=${1}
shift
$cmd "$@"

exit 0
